dependencies:
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 7.3.4
    condition: prometheus.enabled
  - name: grafana
    version: 1.17.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: grafana.enabled
  - name: nginx-ingress
    version: 0.29.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: nginx-ingress.enabled
  - name: chaoskube
    version: 0.10.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: chaoskube.enabled
  - name: fluent-bit
    version: 1.3.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: fluent-bit.enabled
  - name: kibana
    version: 1.1.2
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: kibana.enabled
  - name: seq
    version: 0.1.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: seq.enabled