replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - site.localtest.me
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mini-elasticsearch:
  image:
    tag: 6.5.4
  service:
    name: elasticsearch

kibana:
  enabled: true
  image:
    tag: 6.5.4
  env:
    ELASTICSEARCH_URL: http://elasticsearch:9200
  ingress:
    enabled: true
    hosts:
      - kibana.localtest.me
chaoskube:
  enabled: true
fluent-bit:
  enabled: true
  backend:
    es:
      time_key: '@ts'
    type: es

prometheus:
  enabled: true
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.localtest.me 
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - prometheus-alertmanager.localtest.me

grafana:
  enabled: true
  adminUser: admin
  adminPassword: badpassword🤣
  plugins:
    - grafana-clock-panel
    - grafana-simple-json-datasource
    - grafana-azure-monitor-datasource
  downloadDashboardsImage:
    repository: appropriate/curl
    tag: latest
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    hosts:
      - grafana.localtest.me
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: "http://opsdemo-prometheus-server"
        access: proxy
        isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      some-dashboard:
        json: >
            {"__inputs": [],
            "__requires": [
              {
                "type": "grafana",
                "id": "grafana",
                "name": "Grafana",
                "version": "5.3.2"
              },
              {
                "type": "panel",
                "id": "grafana-clock-panel",
                "name": "Clock",
                "version": "0.1.0"
              }
            ],
            "annotations": {
              "list": [
                {
                  "builtIn": 1,
                  "datasource": "-- Grafana --",
                  "enable": true,
                  "hide": true,
                  "iconColor": "rgba(0, 211, 255, 1)",
                  "name": "Annotations & Alerts",
                  "type": "dashboard"
                }
              ]
            },
            "editable": true,
            "gnetId": null,
            "graphTooltip": 0,
            "id": null,
            "links": [],
            "panels": [
              {
                "bgColor": null,
                "clockType": "24 hour",
                "countdownSettings": {
                  "customFormat": null,
                  "endCountdownTime": "2018-11-16T11:52:00.000Z",
                  "endText": "00:00:00"
                },
                "dateSettings": {
                  "dateFormat": "YYYY-MM-DD",
                  "fontSize": "20px",
                  "fontWeight": "normal",
                  "showDate": false
                },
                "gridPos": {
                  "h": 9,
                  "w": 12,
                  "x": 0,
                  "y": 0
                },
                "id": 2,
                "mode": "time",
                "offsetFromUtc": null,
                "offsetFromUtcMinutes": null,
                "timeSettings": {
                  "customFormat": "HH:mm:ss",
                  "fontSize": "60px",
                  "fontWeight": "normal"
                },
                "title": "Clock",
                "type": "grafana-clock-panel"
              }
            ],
            "schemaVersion": 16,
            "style": "dark",
            "tags": [],
            "templating": {
              "list": []
            },
            "time": {
              "from": "now-6h",
              "to": "now"
            },
            "timepicker": {
              "refresh_intervals": [
                "5s"
              ],
              "time_options": [
                "5m"
              ]
            },
            "timezone": "",
            "title": "Clock",
            "uid": "FZbsFhBmk",
            "version": 1}
      pods:
        gnetId: 4686
        revision: 2
        datasource: Prometheus
      kubernetes-cluster:
        gnetId: 8174
        revision: 1
        datasource: Prometheus
      dashboard-overview:
        url: https://raw.githubusercontent.com/ssaraswati/opsdemo/master/dashboard-overview.json
        datasource: Prometheus
      ingress-dashboard:
        url: https://raw.githubusercontent.com/ssaraswati/opsdemo/master/dashboard-nodes.json
        datasource: Prometheus
      dashboard-ingress:
        url: https://raw.githubusercontent.com/ssaraswati/opsdemo/master/dashboard-ingress.json
        datasource: Prometheus
      dashboard-cluster:
        url: https://raw.githubusercontent.com/ssaraswati/opsdemo/master/dashboard-cluster.json
        datasource: Prometheus

nginx-ingress:
  enabled: true
  controller:
    stats:
      enabled: true
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"

