{
 "title": "Net, Ram and CPU",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Pods network I/O (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (2m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 36 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  }
 ]
}